package ai.hypergraph.shipshape

import org.intellij.lang.annotations.Language

@Language("kt")
fun generateShapes() = """
      |// This file was generated by Shipshape
      |
      |package ai.hypergraph.kotlingrad.shapes
      |
      |import ai.hypergraph.kotlingrad.api.*
      |
      |// Dimensions ================================
      |${genDim()}
      |// Vectors ===================================
      |${genVec()}
      |// Matrices ==================================
      |${genMat()}
      |// Derivatives ===============================
      |${genDif()}
    """.trimMargin()