package edu.mcgill.shipshape

import org.gradle.api.*
import java.io.File

open class Shipshape: Plugin<Project> {
  fun generateShapes(): String {
    val header = """// This file was generated by Shipshape
    
    package edu.umontreal.kotlingrad.shapes
    
    import edu.umontreal.kotlingrad.experimental.SConst
    import edu.umontreal.kotlingrad.experimental.MConst
    import edu.umontreal.kotlingrad.experimental.VConst
    import edu.umontreal.kotlingrad.experimental.RealNumber
    """.trimIndent()

    val shapes = """
      $header
      
      ${genDim()}
      ${genVec()}
      ${genMat()}
    """.trimIndent()

    return shapes
  }

  override fun apply(project: Project) {
    project.run {
      tasks.register("genShapes") {
        // TODO: Parameterize this path
        val shapes = generateShapes()

        val outputDir = "$projectDir/src/main/kotlin/gen"
        try {
          File(outputDir).mkdirs()
          File("$outputDir/Shapes.kt")
            .also { it.createNewFile() }
            .writeText(shapes)
        } catch (e: Exception) {
          logger.error(outputDir)
          throw e
        }
      }
    }
  }
}
