package edu.mcgill.shipshape

fun generateShapes() = """
      |// This file was generated by Shipshape
      |
      |package edu.umontreal.kotlingrad.shapes
      |
      |import edu.umontreal.kotlingrad.api.*
      |
      |// Dimensions ================================
      |${genDim()}
      |// Vectors ===================================
      |${genVec()}
      |// Matrices ==================================
      |${genMat()}
      |// Derivatives ===============================
      |${genDif()}
    """.trimMargin()